"use client";

import { useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { getSupabaseBrowser } from "@/lib/supabase-browser";
import { FileText, Globe2, Mail, Megaphone, Search, Share2, type LucideIcon } from "lucide-react";

type View="overview"|"create"|"templates"|"brand"|"history"|"billing";
type Generation={id:string;title:string;contentType:string;prompt:string;tone:string;content:string;status:string;createdAt:string};
type Brand={name:string;website:string;description:string;audience:string;personality:string;avoidWords:string};
const templateList=["Social post","Paid ad","Email campaign","Product copy","Landing page","SEO metadata"];
const templateIcons:Record<string,LucideIcon>={"Social post":Share2,"Paid ad":Megaphone,"Email campaign":Mail,"Product copy":FileText,"Landing page":Globe2,"SEO metadata":Search};

export default function Home(){
 const[session,setSession]=useState<Session|null>(null),[authReady,setAuthReady]=useState(false),[authMode,setAuthMode]=useState<"signin"|"signup">("signin"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[authError,setAuthError]=useState(""),[busy,setBusy]=useState(false);
 const[view,setView]=useState<View>("overview"),[type,setType]=useState("Social post"),[prompt,setPrompt]=useState(""),[tone,setTone]=useState("Warm & confident"),[result,setResult]=useState(""),[items,setItems]=useState<Generation[]>([]),[toast,setToast]=useState(""),[search,setSearch]=useState(""),[mobile,setMobile]=useState(false),[pendingDelete,setPendingDelete]=useState<string|null>(null),[confirmSignOut,setConfirmSignOut]=useState(false);
 const[brand,setBrand]=useState<Brand>({name:"",website:"",description:"",audience:"",personality:"",avoidWords:""});
 const supabase=useMemo(()=>getSupabaseBrowser(),[]);
 const token=session?.access_token;
 const filtered=items.filter(i=>`${i.title} ${i.contentType}`.toLowerCase().includes(search.toLowerCase()));
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2500)};
 const api=(path:string,init:RequestInit={})=>fetch(path,{...init,headers:{...(init.body?{"Content-Type":"application/json"}:{}),...(token?{Authorization:`Bearer ${token}`}:{})}});

 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthReady(true)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[supabase]);
 useEffect(()=>{if(!token)return;Promise.all([api("/api/generations"),api("/api/brand")]).then(async([g,b])=>{if(g.ok)setItems(await g.json());if(b.ok){const p=await b.json();if(p)setBrand({name:p.name||"",website:p.website||"",description:p.description||"",audience:p.audience||"",personality:p.personality||"",avoidWords:p.avoid_words||""})}})},[token]);

 async function authenticate(e:React.FormEvent){e.preventDefault();setBusy(true);setAuthError("");const action=authMode==="signin"?supabase.auth.signInWithPassword({email,password}):supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}});const{error}=await action;if(error)setAuthError(error.message);else if(authMode==="signup")notify("Check your email to confirm your account");setBusy(false)}
 async function generate(){if(!prompt.trim())return;setBusy(true);setResult("");const r=await api("/api/generate",{method:"POST",body:JSON.stringify({contentType:type,prompt,tone})});const data=await r.json();if(r.ok){setResult(data.generation.content);setItems([{id:data.generation.id,title:data.generation.title,contentType:data.generation.content_type,prompt:data.generation.prompt,tone:data.generation.tone,content:data.generation.content,status:data.generation.status,createdAt:data.generation.created_at},...items]);notify("Generated and saved securely")}else{notify(data.error||"Generation failed");if(data.upgradeRequired)setView("billing")}setBusy(false)}
 async function saveBrand(){setBusy(true);const r=await api("/api/brand",{method:"PUT",body:JSON.stringify(brand)});const data=await r.json();notify(r.ok?"Brand profile saved":data.error||"Unable to save profile");setBusy(false)}
 async function checkout(){setBusy(true);const r=await api("/api/billing/checkout",{method:"POST"});const data=await r.json();if(data.url)location.href=data.url;else notify(data.error||"Checkout unavailable");setBusy(false)}
 async function remove(id:string){setPendingDelete(null);const r=await api(`/api/generations?id=${id}`,{method:"DELETE"});if(r.ok){setItems(items.filter(i=>i.id!==id));notify("Content deleted successfully")}else{const data=await r.json().catch(()=>({}));notify(data.error||"Unable to delete content")}}

 if(!authReady)return <div className="auth-screen"><div className="auth-card"><span className="brand-mark">✦</span><h1>Loading BrandPilot</h1></div></div>;
 if(!session)return <div className="auth-screen"><form className="auth-card" onSubmit={authenticate}><div className="auth-brand"><span className="brand-mark">✦</span><b>BrandPilot</b></div><span className="eyebrow">AI MARKETING WORKSPACE</span><h1>{authMode==="signin"?"Welcome back.":"Create your workspace."}</h1><p>{authMode==="signin"?"Sign in to access your brand and content.":"Start creating on-brand campaigns in minutes."}</p><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></label>{authError&&<div className="auth-error">{authError}</div>}<button className="primary" disabled={busy}>{busy?"Please wait…":authMode==="signin"?"Sign in":"Create account"}</button><button type="button" className="auth-switch" onClick={()=>setAuthMode(authMode==="signin"?"signup":"signin")}>{authMode==="signin"?"New here? Create an account":"Already have an account? Sign in"}</button></form></div>;

 const nav:[View,string,string][]=[["overview","Overview","⌂"],["create","Create content","✦"],["templates","Templates","▦"],["brand","Brand voice","◉"],["history","Content library","◷"]];
 return <main className="app-shell"><aside className={`sidebar ${mobile?"open":""}`}><button className="brand" onClick={()=>setView("overview")}><span className="brand-mark">✦</span>BrandPilot</button><nav><p className="nav-label">Workspace</p>{nav.map(([id,label,icon])=><button key={id} className={view===id?"active":""} onClick={()=>{setView(id);setMobile(false)}}><span>{icon}</span>{label}</button>)}</nav><div className="sidebar-bottom"><button className="upgrade-card" onClick={()=>setView("billing")}><span>✦</span><strong>Grow without limits</strong><small>Upgrade for unlimited creation</small><em>View plans →</em></button><button className="profile" onClick={()=>setConfirmSignOut(true)}><span>{session.user.email?.slice(0,2).toUpperCase()}</span><div><strong>{session.user.email?.split("@")[0]}</strong><small>{session.user.email}</small></div><b>Sign out</b></button></div></aside>
 <section className="workspace"><header className="topbar"><button className="menu" onClick={()=>setMobile(!mobile)}>☰</button><div className="top-title"><b>{nav.find(n=>n[0]===view)?.[1]||"Plans & billing"}</b><span>Secure AI marketing workspace</span></div><button className="primary small" onClick={()=>setView("create")}>✦ Create content</button></header>
 {view==="overview"&&<div className="page"><section className="hero-card"><div><span className="eyebrow">YOUR CREATIVE COPILOT</span><h1>Create better<br/><em>marketing.</em></h1><p>Generate publish-ready content grounded in your real brand voice.</p><button className="dark-button" onClick={()=>setView("create")}>Start creating →</button></div><div className="hero-art"><div className="center-orb">✦</div><div className="ring r1"/><div className="ring r2"/></div></section><section className="stats"><div><span className="stat-icon coral">✦</span><p><strong>{items.length}</strong><small>Pieces created</small></p></div><div><span className="stat-icon green">◉</span><p><strong>{brand.name?"Ready":"Setup"}</strong><small>Brand profile</small></p></div><div><span className="stat-icon violet">◎</span><p><strong>{items.filter(i=>new Date(i.createdAt).getMonth()===new Date().getMonth()).length}</strong><small>This month</small></p></div><div><span className="stat-icon amber">◇</span><p><strong>Secure</strong><small>Private workspace</small></p></div></section><Heading title="Start with a template" text="Choose a proven format."/><section className="template-grid">{templateList.slice(0,4).map((t,i)=><button className="template-card" key={t} onClick={()=>{setType(t);setView("create")}}><span className={`template-icon ${["peach","mint","lilac","yellow"][i]}`}><TemplateIcon name={t}/></span><div><h3>{t}</h3><p>Generate tailored, on-brand {t.toLowerCase()}.</p></div><b>Use template →</b></button>)}</section></div>}
 {view==="create"&&<div className="page"><Intro over="AI CONTENT STUDIO" title="Create publish-ready content." text="Every result uses your saved brand profile and is stored privately."/><div className="creator-grid"><section className="form-card"><label>Content type</label><select value={type} onChange={e=>setType(e.target.value)}>{templateList.map(t=><option key={t}>{t}</option>)}</select><label>Campaign brief</label><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe your offer, goal, audience, and key details…" maxLength={2000}/><small className="counter">{prompt.length}/2000</small><label>Tone</label><div className="tone-row">{["Warm & confident","Playful","Professional"].map(t=><button key={t} className={tone===t?"selected":""} onClick={()=>setTone(t)}>{t}</button>)}</div>{!brand.name&&<div className="brand-note"><span>!</span><p><strong>Complete your brand profile</strong><small>Better inputs produce stronger content.</small></p><button onClick={()=>setView("brand")}>Setup</button></div>}<button className="primary generate" onClick={generate} disabled={busy||!prompt.trim()}>{busy?"Generating with AI…":"✦ Generate & save"}</button></section><section className="result-card">{!result?<div className="empty-result"><span>✦</span><h3>Your generated content appears here</h3><p>Nothing is generated until you submit your brief.</p></div>:<><div className="result-head"><span>Generated copy</span><button onClick={()=>{navigator.clipboard.writeText(result);notify("Copied")}}>Copy</button></div><pre>{result}</pre><div className="result-footer"><span>{tone} · {type}</span><button onClick={generate}>Regenerate</button></div></>}</section></div></div>}
 {view==="templates"&&<div className="page"><Intro over="TEMPLATE LIBRARY" title="Choose your format." text="Every template connects to the production AI generator."/><section className="template-grid large">{templateList.map((t,i)=><button className="template-card" key={t} onClick={()=>{setType(t);setView("create")}}><span className={`template-icon ${["peach","mint","lilac","yellow","blue","rose"][i]}`}><TemplateIcon name={t}/></span><div><h3>{t}</h3><p>Create brand-aware copy from your campaign brief.</p></div><b>Use template →</b></button>)}</section></div>}
 {view==="brand"&&<div className="page"><Intro over="BRAND PROFILE" title="Teach BrandPilot your voice." text="These details are securely applied to every generation."/><section className="settings-card"><div className="settings-head"><div className="logo-block">{brand.name.slice(0,2).toUpperCase()||"BP"}</div><div><h2>{brand.name||"New brand"}</h2><p>Private brand profile</p></div><button onClick={saveBrand} disabled={busy}>Save changes</button></div><div className="settings-grid"><Field label="Brand name" value={brand.name} set={v=>setBrand({...brand,name:v})}/><Field label="Website" value={brand.website} set={v=>setBrand({...brand,website:v})}/><Field label="What do you do?" value={brand.description} set={v=>setBrand({...brand,description:v})} wide area/><Field label="Primary audience" value={brand.audience} set={v=>setBrand({...brand,audience:v})}/><Field label="Brand personality" value={brand.personality} set={v=>setBrand({...brand,personality:v})}/><Field label="Words to avoid" value={brand.avoidWords} set={v=>setBrand({...brand,avoidWords:v})} wide/></div></section></div>}
 {view==="history"&&<div className="page"><Intro over="CONTENT LIBRARY" title="Your saved generations." text="Only content created by your account appears here."/><div className="search-row"><label>⌕<input placeholder="Search content…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><section className="recent-card">{filtered.map(i=><div className="library-row" key={i.id} onClick={()=>{setResult(i.content);setType(i.contentType);setView("create")}}><span className="doc-icon">≡</span><div><strong>{i.title}</strong><small>{i.contentType} · {new Date(i.createdAt).toLocaleDateString()}</small></div><em className="ready">{i.status}</em><button className="delete-button" onClick={e=>{e.stopPropagation();setPendingDelete(i.id)}}>Delete</button></div>)}{!filtered.length&&<div className="no-results">No saved content found.</div>}</section></div>}
 {view==="billing"&&<div className="page"><Intro over="PLANS & BILLING" title="Scale your content engine." text="Payments are securely processed by Stripe." center/><section className="pricing"><article><span>Starter</span><h2>$0<small>/month</small></h2><p>For testing your content workflow.</p><ul><li>✓ 25 AI generations monthly</li><li>✓ Private brand profile</li><li>✓ Content library</li></ul><button>Current plan</button></article><article className="featured"><em>RECOMMENDED</em><span>Pro</span><h2>$29<small>/month</small></h2><p>For active founders and marketers.</p><ul><li>✓ Unlimited generations</li><li>✓ All templates</li><li>✓ Priority AI processing</li><li>✓ Stripe billing portal</li></ul><button onClick={checkout} disabled={busy}>Upgrade securely →</button></article></section></div>}</section>{mobile&&<button className="backdrop" onClick={()=>setMobile(false)}/>} {confirmSignOut&&<div className="modal-backdrop" role="presentation" onClick={()=>setConfirmSignOut(false)}><div className="confirm-modal" role="dialog" aria-modal="true" aria-labelledby="signout-title" onClick={e=>e.stopPropagation()}><span className="modal-icon signout-icon">→</span><h3 id="signout-title">Sign out of BrandPilot?</h3><p>You will need to sign in again to access your brand profile and content library.</p><div className="modal-actions"><button onClick={()=>setConfirmSignOut(false)}>Stay signed in</button><button className="danger" onClick={()=>supabase.auth.signOut()}>Yes, sign out</button></div></div></div>}{pendingDelete&&<div className="modal-backdrop" role="presentation" onClick={()=>setPendingDelete(null)}><div className="confirm-modal" role="dialog" aria-modal="true" aria-labelledby="delete-title" onClick={e=>e.stopPropagation()}><span className="modal-icon">!</span><h3 id="delete-title">Delete this content?</h3><p>This permanently removes the generation from your content library.</p><div className="modal-actions"><button onClick={()=>setPendingDelete(null)}>Keep content</button><button className="danger" onClick={()=>remove(pendingDelete)}>Delete permanently</button></div></div></div>}{toast&&<div className="toast" role="status"><span>✓</span><p>{toast}</p><button aria-label="Dismiss notification" onClick={()=>setToast("")}>×</button></div>}</main>
}

function Intro({over,title,text,center=false}:{over:string;title:string;text:string;center?:boolean}){return <div className={`page-intro ${center?"center":""}`}><span className="eyebrow">{over}</span><h1>{title}</h1><p>{text}</p></div>}
function Heading({title,text}:{title:string;text:string}){return <div className="section-heading"><div><h2>{title}</h2><p>{text}</p></div></div>}
function Field({label,value,set,wide=false,area=false}:{label:string;value:string;set:(v:string)=>void;wide?:boolean;area?:boolean}){return <label className={wide?"wide":""}>{label}{area?<textarea value={value} onChange={e=>set(e.target.value)}/>:<input value={value} onChange={e=>set(e.target.value)}/>}</label>}
function TemplateIcon({name}:{name:string}){const Icon=templateIcons[name]||FileText;return <Icon size={20} strokeWidth={2.2} aria-hidden="true"/>}
