"use client";
import { useEffect, useMemo, useState } from "react";
type View="overview"|"create"|"templates"|"brand"|"history"|"billing";
const nav:{id:View;label:string;icon:string}[]=[{id:"overview",label:"Overview",icon:"⌂"},{id:"create",label:"Create content",icon:"✦"},{id:"templates",label:"Templates",icon:"▦"},{id:"brand",label:"Brand voice",icon:"◉"},{id:"history",label:"Content library",icon:"◷"}];
const templates=[{icon:"◎",title:"Social post",desc:"Scroll-stopping posts for any platform",color:"peach"},{icon:"↗",title:"Paid ad",desc:"High-converting copy for your campaigns",color:"mint"},{icon:"✉",title:"Email campaign",desc:"Emails your audience wants to open",color:"lilac"},{icon:"◇",title:"Product copy",desc:"Turn features into irresistible benefits",color:"yellow"},{icon:"⌁",title:"Landing page",desc:"Clear, compelling website copy",color:"blue"},{icon:"⌕",title:"SEO metadata",desc:"Titles and descriptions that rank",color:"rose"}];
const recent=[{title:"Summer collection launch",type:"Instagram post",status:"Ready",time:"12 min ago"},{title:"Welcome flow — email 01",type:"Email campaign",status:"Draft",time:"Yesterday"},{title:"Linen everyday shirt",type:"Product description",status:"Ready",time:"Aug 16"},{title:"Slow fashion, made simple",type:"Facebook ad",status:"Ready",time:"Aug 14"}];
const outputs:Record<string,string>={"Social post":"Good style shouldn't cost the earth. Meet the everyday layers designed to live in, made responsibly in small batches. Soft on you, lighter on the planet. 🌿\n\nDiscover the new collection →","Paid ad":"The pieces you'll reach for on repeat. Thoughtful materials, timeless fits, and free exchanges. Meet your new everyday wardrobe.","Email campaign":"Subject: Your new everyday favorites have arrived\n\nWe made getting dressed easier. Discover versatile pieces that feel as good as they look—crafted responsibly and designed to last.","Product copy":"An effortless essential, thoughtfully made. Our Everyday Shirt pairs breathable organic cotton with a relaxed, wear-anywhere silhouette.","Landing page":"Feel good in what you wear.\n\nTimeless essentials, responsibly made for real life. Build a wardrobe you love—without compromising your values.","SEO metadata":"Sustainable Everyday Clothing | North & Kind\n\nShop timeless, responsibly made essentials crafted from better materials. Free shipping on orders over $75."};
export default function Home(){
 const[view,setView]=useState<View>("overview"),[mobile,setMobile]=useState(false),[type,setType]=useState("Social post"),[prompt,setPrompt]=useState("Announce our new summer collection of sustainable everyday essentials."),[tone,setTone]=useState("Warm & confident"),[result,setResult]=useState(""),[generating,setGenerating]=useState(false),[saved,setSaved]=useState(false),[toast,setToast]=useState(""),[search,setSearch]=useState(""),[library,setLibrary]=useState(recent);
 const filtered=useMemo(()=>library.filter(r=>`${r.title} ${r.type}`.toLowerCase().includes(search.toLowerCase())),[search,library]);
 useEffect(()=>{fetch("/api/generations").then(r=>r.ok?r.json():[]).then((rows:Array<{title:string;contentType:string;status:string;createdAt:string}>)=>{if(rows.length)setLibrary(rows.map(r=>({title:r.title,type:r.contentType,status:r.status,time:new Date(r.createdAt).toLocaleDateString()})))}).catch(()=>{})},[]);
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2200)};
 const generate=()=>{setGenerating(true);setResult("");setTimeout(()=>{setResult(outputs[type]||outputs["Social post"]);setGenerating(false);setSaved(false)},850)};
 const saveGeneration=async()=>{try{const response=await fetch("/api/generations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:prompt.slice(0,55),contentType:type,prompt,tone,content:result})});if(!response.ok)throw new Error();setSaved(true);setLibrary([{title:prompt.slice(0,55),type,status:"Ready",time:"Just now"},...library]);notify("Saved to your Supabase library")}catch{notify("Connect Supabase, then try saving again")}};
 const saveBrand=async()=>{try{const response=await fetch("/api/brand",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:"North & Kind",website:"northandkind.co",description:"We make timeless, sustainable everyday clothing for thoughtful people.",audience:"Conscious shoppers, 25–44",personality:"Warm, intentional, optimistic",avoidWords:"cheap, must-have, hurry, revolutionary"})});if(!response.ok)throw new Error();notify("Brand profile saved to Supabase")}catch{notify("Connect Supabase, then try saving again")}};
 const choose=(t:string)=>{setType(t);setView("create")};
 return <main className="app-shell"><aside className={`sidebar ${mobile?"open":""}`}><button className="brand" onClick={()=>{setView("overview");setMobile(false)}}><span className="brand-mark">✦</span>BrandPilot</button><nav><p className="nav-label">Workspace</p>{nav.map(n=><button key={n.id} className={view===n.id?"active":""} onClick={()=>{setView(n.id);setMobile(false)}}><span>{n.icon}</span>{n.label}</button>)}</nav><div className="sidebar-bottom"><button className="upgrade-card" onClick={()=>setView("billing")}><span>✦</span><strong>Unlock more ideas</strong><small>Upgrade for unlimited creation</small><em>View plans →</em></button><button className="profile" onClick={()=>setView("brand")}><span>AK</span><div><strong>Alex Kim</strong><small>alex@northandkind.co</small></div><b>•••</b></button></div></aside>
 <section className="workspace"><header className="topbar"><button className="menu" aria-label="Open menu" onClick={()=>setMobile(!mobile)}>☰</button><div className="top-title"><b>{view==="overview"?"Good morning, Alex":nav.find(n=>n.id===view)?.label||"Plans & billing"}</b><span>{view==="overview"?"Let's make something worth sharing.":"Your AI marketing workspace"}</span></div><div className="top-actions"><button className="icon-button" aria-label="Notifications" onClick={()=>notify("You're all caught up")}>♢<i/></button><button className="primary small" onClick={()=>setView("create")}>✦ Create content</button></div></header>
 {view==="overview"&&<div className="page"><section className="hero-card"><div><span className="eyebrow">YOUR CREATIVE COPILOT</span><h1>What will we<br/>create <em>today?</em></h1><p>Turn a simple idea into polished, on-brand content in seconds.</p><button className="dark-button" onClick={()=>setView("create")}>Start creating <span>→</span></button></div><div className="hero-art" aria-hidden="true"><div className="spark s1">✦</div><div className="spark s2">✦</div><div className="orbit one">Aa</div><div className="orbit two">♥</div><div className="orbit three">↗</div><div className="center-orb">✦</div><div className="ring r1"/><div className="ring r2"/></div></section><section className="stats"><div><span className="stat-icon coral">✦</span><p><strong>38</strong><small>Pieces created</small></p><b>+12% ↗</b></div><div><span className="stat-icon green">◷</span><p><strong>4.2h</strong><small>Time saved</small></p><b>+18% ↗</b></div><div><span className="stat-icon violet">◎</span><p><strong>92%</strong><small>Brand match</small></p><b>Excellent</b></div><div><span className="stat-icon amber">◇</span><p><strong>62</strong><small>Credits left</small></p><button onClick={()=>setView("billing")}>Manage</button></div></section><Heading title="Start with a template" text="Pick a format and let BrandPilot do the heavy lifting." action="View all templates →" click={()=>setView("templates")}/><section className="template-grid">{templates.slice(0,4).map(t=><Template key={t.title} t={t} click={()=>choose(t.title)}/>)}</section><Heading title="Recent content" text="Jump back into your latest work." action="View content library →" click={()=>setView("history")} compact/><Recent items={recent.slice(0,3)} click={()=>setView("create")}/></div>}
 {view==="create"&&<div className="page"><Intro over="AI CONTENT STUDIO" title="Create something brilliant." text="Give us the idea. We’ll shape it in your brand voice."/><div className="creator-grid"><section className="form-card"><label>Content type</label><select value={type} onChange={e=>setType(e.target.value)}>{templates.map(t=><option key={t.title}>{t.title}</option>)}</select><label>What are you creating?</label><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={500}/><small className="counter">{prompt.length}/500</small><label>Tone of voice</label><div className="tone-row">{["Warm & confident","Playful","Professional"].map(t=><button className={tone===t?"selected":""} onClick={()=>setTone(t)} key={t}>{t}</button>)}</div><div className="brand-note"><span>◉</span><p><strong>North & Kind brand voice applied</strong><small>Warm, intentional, human — never salesy.</small></p><button onClick={()=>setView("brand")}>Edit</button></div><button className="primary generate" onClick={generate} disabled={!prompt.trim()||generating}>{generating?"Creating your content…":"✦ Generate content"}</button></section><section className="result-card">{!result&&!generating&&<div className="empty-result"><span>✦</span><h3>Your content will appear here</h3><p>Fill in the brief and let the ideas flow.</p></div>}{generating&&<div className="loading-copy"><i/><i/><i/><i/></div>}{result&&<><div className="result-head"><span>Generated copy</span><div><button onClick={()=>{navigator.clipboard?.writeText(result);notify("Copied to clipboard")}}>Copy</button><button onClick={saveGeneration}>{saved?"Saved ✓":"Save"}</button></div></div><pre>{result}</pre><div className="result-footer"><span>{tone} · {type}</span><button onClick={generate}>↻ Regenerate</button></div></>}</section></div></div>}
 {view==="templates"&&<div className="page"><Intro over="TEMPLATE LIBRARY" title="Your shortcut to great content." text="Proven frameworks, ready for your brand."/><div className="filter-row"><button className="active">All templates</button><button>Social</button><button>Ads</button><button>Email</button><button>Website</button></div><section className="template-grid large">{templates.map(t=><Template key={t.title} t={t} click={()=>choose(t.title)}/>)}</section></div>}
 {view==="brand"&&<div className="page"><Intro over="BRAND PROFILE" title="Sound unmistakably like you." text="BrandPilot uses these details in every generation."/><section className="settings-card"><div className="settings-head"><div className="logo-block">N&K</div><div><h2>North & Kind</h2><p>Active brand profile</p></div><button onClick={saveBrand}>Save changes</button></div><div className="settings-grid"><label>Brand name<input defaultValue="North & Kind"/></label><label>Website<input defaultValue="northandkind.co"/></label><label className="wide">What do you do?<textarea defaultValue="We make timeless, sustainable everyday clothing for thoughtful people."/></label><label>Primary audience<input defaultValue="Conscious shoppers, 25–44"/></label><label>Brand personality<input defaultValue="Warm, intentional, optimistic"/></label><label className="wide">Words to avoid<input defaultValue="cheap, must-have, hurry, revolutionary"/></label></div><div className="voice-preview"><span>✦</span><div><strong>Your voice, summarized</strong><p>Calm confidence with a human touch. Clear, grounded language that inspires without pushing. Optimistic, but never over-polished.</p></div></div></section></div>}
 {view==="history"&&<div className="page"><div className="library-head"><Intro over="CONTENT LIBRARY" title="Everything you’ve created." text="Find, reuse, and export your best ideas."/><button className="primary" onClick={()=>setView("create")}>✦ New content</button></div><div className="search-row"><label>⌕<input placeholder="Search your content…" value={search} onChange={e=>setSearch(e.target.value)}/></label><button onClick={()=>notify("Export prepared")}>Export all ↗</button></div><Recent items={filtered} click={()=>setView("create")}/>{!filtered.length&&<div className="no-results">No content matches “{search}”.</div>}</div>}
 {view==="billing"&&<div className="page"><Intro over="SIMPLE PRICING" title="Make more. Market better." text="Start free, then grow when you’re ready." center/><section className="pricing"><Plan name="Starter" price="$0" text="For trying out your creative copilot." features={["25 generations / month","1 brand profile","All core templates","Copy & export"]} button="Current plan" click={()=>notify("You're already on Starter")}/><Plan featured name="Pro" price="$29" text="For founders and growing marketing teams." features={["Unlimited generations","5 brand profiles","Premium templates","Campaign collections","Priority AI processing"]} button="Upgrade to Pro →" click={()=>notify("Checkout ready for payment connection")}/><Plan name="Studio" price="$79" text="For teams managing multiple brands." features={["Everything in Pro","Unlimited brand profiles","5 team members","Shared content library","Priority support"]} button="Talk to sales" click={()=>notify("Sales request started")}/></section></div>}</section>{mobile&&<button className="backdrop" aria-label="Close menu" onClick={()=>setMobile(false)}/>} {toast&&<div className="toast">✓ {toast}</div>}</main>}
function Intro({over,title,text,center=false}:{over:string;title:string;text:string;center?:boolean}){return <div className={`page-intro ${center?"center":""}`}><span className="eyebrow">{over}</span><h1>{title}</h1><p>{text}</p></div>}
function Heading({title,text,action,click,compact=false}:{title:string;text:string;action:string;click:()=>void;compact?:boolean}){return <div className={`section-heading ${compact?"compact":""}`}><div><h2>{title}</h2><p>{text}</p></div><button onClick={click}>{action}</button></div>}
function Template({t,click}:{t:(typeof templates)[0];click:()=>void}){return <button className="template-card" onClick={click}><span className={`template-icon ${t.color}`}>{t.icon}</span><div><h3>{t.title}</h3><p>{t.desc}</p></div><b>Use template →</b></button>}
function Recent({items,click}:{items:typeof recent;click:()=>void}){return <section className="recent-card">{items.map(r=><button key={r.title} onClick={click}><span className="doc-icon">≡</span><div><strong>{r.title}</strong><small>{r.type} · {r.time}</small></div><em className={r.status==="Draft"?"draft":"ready"}>{r.status}</em><b>Open →</b></button>)}</section>}
function Plan({name,price,text,features,button,click,featured=false}:{name:string;price:string;text:string;features:string[];button:string;click:()=>void;featured?:boolean}){return <article className={featured?"featured":""}>{featured&&<em>BEST VALUE</em>}<span>{name}</span><h2>{price}<small>/month</small></h2><p>{text}</p><ul>{features.map(f=><li key={f}>✓ {f}</li>)}</ul><button onClick={click}>{button}</button></article>}


